alter table "public"."profiles" drop constraint "profiles_username_key";

alter table "public"."profiles" drop constraint "username_length";

alter table "public"."sessions" drop constraint "sessions_track_id_fkey";

drop function if exists "public"."calc_min_g_force_x"(session_id_input uuid);

drop index if exists "public"."profiles_username_key";


  create table "public"."app_stats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "total_sessions" smallint,
    "total_laps" smallint,
    "total_tracks" smallint,
    "total_users" smallint
      );


alter table "public"."app_stats" enable row level security;

alter table "public"."laps" add column "track_id" uuid;

alter table "public"."profiles" drop column "full_name";

alter table "public"."profiles" drop column "username";

alter table "public"."profiles" add column "first_name" text;

alter table "public"."profiles" add column "last_name" text;

alter table "public"."sessions" drop column "file_name";

alter table "public"."sessions" add column "session_source" text;

CREATE UNIQUE INDEX app_stats_pkey ON public.app_stats USING btree (id);

alter table "public"."app_stats" add constraint "app_stats_pkey" PRIMARY KEY using index "app_stats_pkey";

alter table "public"."laps" add constraint "laps_track_id_fkey" FOREIGN KEY (track_id) REFERENCES public.tracks(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."laps" validate constraint "laps_track_id_fkey";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(first_name) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

alter table "public"."sessions" add constraint "sessions_track_id_fkey" FOREIGN KEY (track_id) REFERENCES public.tracks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sessions" validate constraint "sessions_track_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  insert into public.profiles (id, first_name, last_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;$function$
;

grant delete on table "public"."app_stats" to "anon";

grant insert on table "public"."app_stats" to "anon";

grant references on table "public"."app_stats" to "anon";

grant select on table "public"."app_stats" to "anon";

grant trigger on table "public"."app_stats" to "anon";

grant truncate on table "public"."app_stats" to "anon";

grant update on table "public"."app_stats" to "anon";

grant delete on table "public"."app_stats" to "authenticated";

grant insert on table "public"."app_stats" to "authenticated";

grant references on table "public"."app_stats" to "authenticated";

grant select on table "public"."app_stats" to "authenticated";

grant trigger on table "public"."app_stats" to "authenticated";

grant truncate on table "public"."app_stats" to "authenticated";

grant update on table "public"."app_stats" to "authenticated";

grant delete on table "public"."app_stats" to "service_role";

grant insert on table "public"."app_stats" to "service_role";

grant references on table "public"."app_stats" to "service_role";

grant select on table "public"."app_stats" to "service_role";

grant trigger on table "public"."app_stats" to "service_role";

grant truncate on table "public"."app_stats" to "service_role";

grant update on table "public"."app_stats" to "service_role";


  create policy "Enable read access for all users"
  on "public"."app_stats"
  as permissive
  for select
  to public
using (true);



