


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."app_role" AS ENUM (
    'admin',
    'team',
    'user'
);


ALTER TYPE "public"."app_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$begin
  insert into public.profiles (id, email, first_name, last_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'email', new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_stats" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "total_sessions" smallint NOT NULL,
    "total_laps" smallint NOT NULL,
    "total_tracks" smallint NOT NULL,
    "total_users" smallint NOT NULL
);


ALTER TABLE "public"."app_stats" OWNER TO "postgres";


ALTER TABLE "public"."app_stats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_stats_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."comment_reactions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "comment_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "reaction" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."comment_reactions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dm_messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "thread_id" "uuid" NOT NULL,
    "sender_id" "uuid" NOT NULL,
    "body" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "edited_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."dm_messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dm_participants" (
    "thread_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."dm_participants" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dm_threads" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."dm_threads" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."laps" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "session_id" "uuid",
    "lap_number" integer NOT NULL,
    "lap_time_seconds" numeric(10,3) NOT NULL,
    "max_lean_angle" numeric(5,2) NOT NULL,
    "max_speed_kmh" numeric(6,2) NOT NULL,
    "max_g_force_x" numeric(5,3) NOT NULL,
    "max_g_force_z" numeric(5,3) NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "min_g_force_x" numeric(5,3) DEFAULT '0'::numeric NOT NULL,
    "min_g_force_z" numeric(5,3) DEFAULT '0'::numeric NOT NULL,
    "min_speed_kmh" numeric(6,2) DEFAULT '0'::numeric NOT NULL,
    "track_id" "uuid" NOT NULL,
    "sectors" numeric[] NOT NULL
);


ALTER TABLE "public"."laps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."news_posts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "author_id" "uuid",
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "content" "text" NOT NULL,
    "cover_url" "text",
    "tags" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "published_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."news_posts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "avatar_url" "text",
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "role" "public"."app_role" DEFAULT 'user'::"public"."app_role" NOT NULL,
    CONSTRAINT "username_length" CHECK (("char_length"("first_name") >= 3))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."session_comments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "session_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "parent_id" "uuid",
    "body" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."session_comments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sessions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "track_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "data_source" "text",
    "session_date" timestamp with time zone NOT NULL,
    "session_type" "text" DEFAULT 'Track'::"text" NOT NULL,
    "total_laps" integer DEFAULT 0 NOT NULL,
    "best_lap_time_seconds" numeric(10,3) NOT NULL,
    "vehicle" "text",
    "duration_seconds" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "session_source" "text",
    "theoretical_best_lap_time_seconds" numeric DEFAULT '0'::numeric NOT NULL
);


ALTER TABLE "public"."sessions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."telemetry_points" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "session_id" "uuid" NOT NULL,
    "lap_id" "uuid" NOT NULL,
    "record_number" integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "altitude" numeric(8,2) DEFAULT '0'::numeric NOT NULL,
    "speed_kmh" numeric(6,2) NOT NULL,
    "g_force_x" numeric(5,3) NOT NULL,
    "g_force_z" numeric(5,3) NOT NULL,
    "lap_number" integer NOT NULL,
    "lean_angle" numeric(5,2) NOT NULL,
    "gyro_x" numeric(8,3) NOT NULL,
    "gyro_y" numeric(8,3) NOT NULL,
    "gyro_z" numeric(8,3) NOT NULL,
    "gps_point" "jsonb" NOT NULL
);


ALTER TABLE "public"."telemetry_points" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tracks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "country" "text" NOT NULL,
    "length_meters" numeric(10,2) DEFAULT '0'::numeric NOT NULL,
    "turns" integer DEFAULT 0 NOT NULL,
    "configuration" "text",
    "image_url" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "gps_point" "jsonb",
    "slug" character varying NOT NULL
);


ALTER TABLE "public"."tracks" OWNER TO "postgres";


ALTER TABLE ONLY "public"."app_stats"
    ADD CONSTRAINT "app_stats_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_unique" UNIQUE ("comment_id", "user_id", "reaction");



ALTER TABLE ONLY "public"."dm_messages"
    ADD CONSTRAINT "dm_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dm_participants"
    ADD CONSTRAINT "dm_participants_pkey" PRIMARY KEY ("thread_id", "user_id");



ALTER TABLE ONLY "public"."dm_threads"
    ADD CONSTRAINT "dm_threads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."laps"
    ADD CONSTRAINT "laps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."news_posts"
    ADD CONSTRAINT "news_posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."session_comments"
    ADD CONSTRAINT "session_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."telemetry_points"
    ADD CONSTRAINT "telemetry_points_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracks"
    ADD CONSTRAINT "tracks_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tracks"
    ADD CONSTRAINT "tracks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracks"
    ADD CONSTRAINT "tracks_slug_key" UNIQUE ("slug");



CREATE INDEX "idx_comment_reactions_comment_id" ON "public"."comment_reactions" USING "btree" ("comment_id");



CREATE INDEX "idx_dm_messages_thread_id" ON "public"."dm_messages" USING "btree" ("thread_id");



CREATE INDEX "idx_dm_participants_user_id" ON "public"."dm_participants" USING "btree" ("user_id");



CREATE INDEX "idx_laps_lap_number" ON "public"."laps" USING "btree" ("lap_number");



CREATE INDEX "idx_laps_session_id" ON "public"."laps" USING "btree" ("session_id");



CREATE INDEX "idx_session_comments_created_at" ON "public"."session_comments" USING "btree" ("created_at");



CREATE INDEX "idx_session_comments_parent_id" ON "public"."session_comments" USING "btree" ("parent_id");



CREATE INDEX "idx_session_comments_session_id" ON "public"."session_comments" USING "btree" ("session_id");



CREATE INDEX "idx_sessions_session_date" ON "public"."sessions" USING "btree" ("session_date");



CREATE INDEX "idx_sessions_track_id" ON "public"."sessions" USING "btree" ("track_id");



CREATE INDEX "idx_telemetry_lap_id" ON "public"."telemetry_points" USING "btree" ("lap_id");



CREATE INDEX "idx_telemetry_session_id" ON "public"."telemetry_points" USING "btree" ("session_id");



CREATE INDEX "idx_telemetry_timestamp" ON "public"."telemetry_points" USING "btree" ("timestamp");



CREATE UNIQUE INDEX "news_posts_slug_key" ON "public"."news_posts" USING "btree" ("slug");



ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "public"."session_comments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dm_messages"
    ADD CONSTRAINT "dm_messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dm_messages"
    ADD CONSTRAINT "dm_messages_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "public"."dm_threads"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dm_participants"
    ADD CONSTRAINT "dm_participants_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "public"."dm_threads"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dm_participants"
    ADD CONSTRAINT "dm_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dm_threads"
    ADD CONSTRAINT "dm_threads_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."laps"
    ADD CONSTRAINT "laps_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."laps"
    ADD CONSTRAINT "laps_track_id_fkey" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."news_posts"
    ADD CONSTRAINT "news_posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."session_comments"
    ADD CONSTRAINT "session_comments_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."session_comments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."session_comments"
    ADD CONSTRAINT "session_comments_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."session_comments"
    ADD CONSTRAINT "session_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_track_id_fkey" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."telemetry_points"
    ADD CONSTRAINT "telemetry_points_lap_id_fkey" FOREIGN KEY ("lap_id") REFERENCES "public"."laps"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."telemetry_points"
    ADD CONSTRAINT "telemetry_points_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;



CREATE POLICY "Admins update tracks" ON "public"."tracks" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))));



CREATE POLICY "Authenticated read comment reactions" ON "public"."comment_reactions" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated read laps" ON "public"."laps" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated read session comments" ON "public"."session_comments" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated read sessions" ON "public"."sessions" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated read telemetry" ON "public"."telemetry_points" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated read tracks" ON "public"."tracks" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable read access for all users" ON "public"."app_stats" FOR SELECT USING (true);



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Public read news posts" ON "public"."news_posts" FOR SELECT USING (true);



CREATE POLICY "Team and admin manage news posts" ON "public"."news_posts" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = ANY (ARRAY['admin'::"public"."app_role", 'team'::"public"."app_role"])))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = ANY (ARRAY['admin'::"public"."app_role", 'team'::"public"."app_role"]))))));



CREATE POLICY "Users add dm participants" ON "public"."dm_participants" FOR INSERT WITH CHECK ((("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."dm_threads" "t"
  WHERE (("t"."id" = "dm_participants"."thread_id") AND ("t"."created_by" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role"))))));



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users create dm threads" ON "public"."dm_threads" FOR INSERT WITH CHECK (("auth"."uid"() = "created_by"));



CREATE POLICY "Users delete own dm messages" ON "public"."dm_messages" FOR DELETE USING ((("auth"."uid"() = "sender_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role"))))));



CREATE POLICY "Users delete own dm threads" ON "public"."dm_threads" FOR DELETE USING ((("auth"."uid"() = "created_by") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role"))))));



CREATE POLICY "Users delete own laps" ON "public"."laps" FOR DELETE USING ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."sessions" "s"
  WHERE (("s"."id" = "laps"."session_id") AND ("s"."user_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users delete own session comments" ON "public"."session_comments" FOR DELETE USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users delete own sessions" ON "public"."sessions" FOR DELETE USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users delete own telemetry" ON "public"."telemetry_points" FOR DELETE USING ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."sessions" "s"
  WHERE (("s"."id" = "telemetry_points"."session_id") AND ("s"."user_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users edit own dm messages" ON "public"."dm_messages" FOR UPDATE USING ((("auth"."uid"() = "sender_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role"))))));



CREATE POLICY "Users insert own laps" ON "public"."laps" FOR INSERT WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."sessions" "s"
  WHERE (("s"."id" = "laps"."session_id") AND ("s"."user_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users insert own session comments" ON "public"."session_comments" FOR INSERT WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND ("auth"."uid"() = "user_id")));



CREATE POLICY "Users insert own sessions" ON "public"."sessions" FOR INSERT WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users insert own telemetry" ON "public"."telemetry_points" FOR INSERT WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."sessions" "s"
  WHERE (("s"."id" = "telemetry_points"."session_id") AND ("s"."user_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users insert tracks" ON "public"."tracks" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Users react" ON "public"."comment_reactions" FOR INSERT WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND ("auth"."uid"() = "user_id")));



CREATE POLICY "Users read dm messages" ON "public"."dm_messages" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."dm_participants" "p"
  WHERE (("p"."thread_id" = "p"."thread_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users read dm participants" ON "public"."dm_participants" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."dm_participants" "p"
  WHERE (("p"."thread_id" = "p"."thread_id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users read dm threads" ON "public"."dm_threads" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."dm_participants" "p"
  WHERE (("p"."thread_id" = "dm_threads"."id") AND ("p"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users remove dm participants" ON "public"."dm_participants" FOR DELETE USING ((("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."dm_threads" "t"
  WHERE (("t"."id" = "dm_participants"."thread_id") AND ("t"."created_by" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role"))))));



CREATE POLICY "Users remove own reactions" ON "public"."comment_reactions" FOR DELETE USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users send dm messages" ON "public"."dm_messages" FOR INSERT WITH CHECK ((("auth"."uid"() = "sender_id") AND (EXISTS ( SELECT 1
   FROM "public"."dm_participants" "p"
  WHERE (("p"."thread_id" = "p"."thread_id") AND ("p"."user_id" = "auth"."uid"()))))));



CREATE POLICY "Users update own laps" ON "public"."laps" FOR UPDATE USING ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."sessions" "s"
  WHERE (("s"."id" = "laps"."session_id") AND ("s"."user_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users update own session comments" ON "public"."session_comments" FOR UPDATE USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users update own sessions" ON "public"."sessions" FOR UPDATE USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



CREATE POLICY "Users update own telemetry" ON "public"."telemetry_points" FOR UPDATE USING ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."sessions" "s"
  WHERE (("s"."id" = "telemetry_points"."session_id") AND ("s"."user_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = "auth"."uid"()) AND ("p"."role" = 'admin'::"public"."app_role")))))));



ALTER TABLE "public"."app_stats" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."comment_reactions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dm_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dm_participants" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dm_threads" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."laps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."news_posts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."session_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sessions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."telemetry_points" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tracks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."app_stats" TO "anon";
GRANT ALL ON TABLE "public"."app_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."app_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_stats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_stats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_stats_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."comment_reactions" TO "anon";
GRANT ALL ON TABLE "public"."comment_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."comment_reactions" TO "service_role";



GRANT ALL ON TABLE "public"."dm_messages" TO "anon";
GRANT ALL ON TABLE "public"."dm_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."dm_messages" TO "service_role";



GRANT ALL ON TABLE "public"."dm_participants" TO "anon";
GRANT ALL ON TABLE "public"."dm_participants" TO "authenticated";
GRANT ALL ON TABLE "public"."dm_participants" TO "service_role";



GRANT ALL ON TABLE "public"."dm_threads" TO "anon";
GRANT ALL ON TABLE "public"."dm_threads" TO "authenticated";
GRANT ALL ON TABLE "public"."dm_threads" TO "service_role";



GRANT ALL ON TABLE "public"."laps" TO "anon";
GRANT ALL ON TABLE "public"."laps" TO "authenticated";
GRANT ALL ON TABLE "public"."laps" TO "service_role";



GRANT ALL ON TABLE "public"."news_posts" TO "anon";
GRANT ALL ON TABLE "public"."news_posts" TO "authenticated";
GRANT ALL ON TABLE "public"."news_posts" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."session_comments" TO "anon";
GRANT ALL ON TABLE "public"."session_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."session_comments" TO "service_role";



GRANT ALL ON TABLE "public"."sessions" TO "anon";
GRANT ALL ON TABLE "public"."sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."sessions" TO "service_role";



GRANT ALL ON TABLE "public"."telemetry_points" TO "anon";
GRANT ALL ON TABLE "public"."telemetry_points" TO "authenticated";
GRANT ALL ON TABLE "public"."telemetry_points" TO "service_role";



GRANT ALL ON TABLE "public"."tracks" TO "anon";
GRANT ALL ON TABLE "public"."tracks" TO "authenticated";
GRANT ALL ON TABLE "public"."tracks" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
































--
-- Dumped schema changes for auth and storage
--

CREATE OR REPLACE TRIGGER "on_auth_user_created" AFTER INSERT ON "auth"."users" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_user"();



CREATE POLICY "Anyone can upload an avatar." ON "storage"."objects" FOR INSERT WITH CHECK (("bucket_id" = 'avatars'::"text"));



CREATE POLICY "Avatar images are publicly accessible." ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'avatars'::"text"));



CREATE POLICY "Give users access to own folder 1oj01fe_0" ON "storage"."objects" FOR DELETE USING ((("bucket_id" = 'avatars'::"text") AND (( SELECT ("auth"."uid"())::"text" AS "uid") = ("storage"."foldername"("name"))[1])));



CREATE POLICY "Give users access to own folder 1oj01fe_1" ON "storage"."objects" FOR SELECT USING ((("bucket_id" = 'avatars'::"text") AND (( SELECT ("auth"."uid"())::"text" AS "uid") = ("storage"."foldername"("name"))[1])));



