


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$begin
  insert into public.profiles (id, email, first_name, last_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'email', new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_stats" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "total_sessions" smallint NOT NULL,
    "total_laps" smallint NOT NULL,
    "total_tracks" smallint NOT NULL,
    "total_users" smallint NOT NULL
);


ALTER TABLE "public"."app_stats" OWNER TO "postgres";


ALTER TABLE "public"."app_stats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_stats_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."laps" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "session_id" "uuid",
    "lap_number" integer NOT NULL,
    "lap_time_seconds" numeric(10,3) NOT NULL,
    "max_lean_angle" numeric(5,2) NOT NULL,
    "max_speed_kmh" numeric(6,2) NOT NULL,
    "max_g_force_x" numeric(5,3) NOT NULL,
    "max_g_force_z" numeric(5,3) NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "min_g_force_x" numeric(5,3) DEFAULT '0'::numeric NOT NULL,
    "min_g_force_z" numeric(5,3) DEFAULT '0'::numeric NOT NULL,
    "min_speed_kmh" numeric(6,2) DEFAULT '0'::numeric NOT NULL,
    "track_id" "uuid" NOT NULL,
    "sectors" numeric[] NOT NULL
);


ALTER TABLE "public"."laps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "avatar_url" "text",
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    CONSTRAINT "username_length" CHECK (("char_length"("first_name") >= 3))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sessions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "track_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "data_source" "text",
    "session_date" timestamp with time zone NOT NULL,
    "session_type" "text" DEFAULT 'Track'::"text" NOT NULL,
    "total_laps" integer DEFAULT 0 NOT NULL,
    "best_lap_time_seconds" numeric(10,3) NOT NULL,
    "vehicle" "text",
    "duration_seconds" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "session_source" "text",
    "theoretical_best_lap_time_seconds" numeric DEFAULT '0'::numeric NOT NULL
);


ALTER TABLE "public"."sessions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."telemetry_points" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "session_id" "uuid" NOT NULL,
    "lap_id" "uuid" NOT NULL,
    "record_number" integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "altitude" numeric(8,2) DEFAULT '0'::numeric NOT NULL,
    "speed_kmh" numeric(6,2) NOT NULL,
    "g_force_x" numeric(5,3) NOT NULL,
    "g_force_z" numeric(5,3) NOT NULL,
    "lap_number" integer NOT NULL,
    "lean_angle" numeric(5,2) NOT NULL,
    "gyro_x" numeric(8,3) NOT NULL,
    "gyro_y" numeric(8,3) NOT NULL,
    "gyro_z" numeric(8,3) NOT NULL,
    "gps_point" "jsonb" NOT NULL
);


ALTER TABLE "public"."telemetry_points" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tracks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "country" "text" NOT NULL,
    "length_meters" numeric(10,2) DEFAULT '0'::numeric NOT NULL,
    "turns" integer DEFAULT 0 NOT NULL,
    "configuration" "text",
    "image_url" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "gps_point" "jsonb",
    "track_slug" character varying NOT NULL
);


ALTER TABLE "public"."tracks" OWNER TO "postgres";


ALTER TABLE ONLY "public"."app_stats"
    ADD CONSTRAINT "app_stats_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."laps"
    ADD CONSTRAINT "laps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."telemetry_points"
    ADD CONSTRAINT "telemetry_points_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracks"
    ADD CONSTRAINT "tracks_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tracks"
    ADD CONSTRAINT "tracks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracks"
    ADD CONSTRAINT "tracks_track_slug_key" UNIQUE ("track_slug");



CREATE INDEX "idx_laps_lap_number" ON "public"."laps" USING "btree" ("lap_number");



CREATE INDEX "idx_laps_session_id" ON "public"."laps" USING "btree" ("session_id");



CREATE INDEX "idx_sessions_session_date" ON "public"."sessions" USING "btree" ("session_date");



CREATE INDEX "idx_sessions_track_id" ON "public"."sessions" USING "btree" ("track_id");



CREATE INDEX "idx_telemetry_lap_id" ON "public"."telemetry_points" USING "btree" ("lap_id");



CREATE INDEX "idx_telemetry_session_id" ON "public"."telemetry_points" USING "btree" ("session_id");



CREATE INDEX "idx_telemetry_timestamp" ON "public"."telemetry_points" USING "btree" ("timestamp");



ALTER TABLE ONLY "public"."laps"
    ADD CONSTRAINT "laps_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."laps"
    ADD CONSTRAINT "laps_track_id_fkey" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_track_id_fkey" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."telemetry_points"
    ADD CONSTRAINT "telemetry_points_lap_id_fkey" FOREIGN KEY ("lap_id") REFERENCES "public"."laps"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."telemetry_points"
    ADD CONSTRAINT "telemetry_points_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE CASCADE;



CREATE POLICY "Allow public insert on laps" ON "public"."laps" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on sessions" ON "public"."sessions" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on telemetry" ON "public"."telemetry_points" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on tracks" ON "public"."tracks" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public read access on laps" ON "public"."laps" FOR SELECT USING (true);



CREATE POLICY "Allow public read access on sessions" ON "public"."sessions" FOR SELECT USING (true);



CREATE POLICY "Allow public read access on telemetry" ON "public"."telemetry_points" FOR SELECT USING (true);



CREATE POLICY "Allow public read access on tracks" ON "public"."tracks" FOR SELECT USING (true);



CREATE POLICY "Allow public update on sessions" ON "public"."sessions" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on tracks" ON "public"."tracks" FOR UPDATE USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."app_stats" FOR SELECT USING (true);



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



ALTER TABLE "public"."app_stats" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."laps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sessions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."telemetry_points" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tracks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."app_stats" TO "anon";
GRANT ALL ON TABLE "public"."app_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."app_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_stats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_stats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_stats_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."laps" TO "anon";
GRANT ALL ON TABLE "public"."laps" TO "authenticated";
GRANT ALL ON TABLE "public"."laps" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."sessions" TO "anon";
GRANT ALL ON TABLE "public"."sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."sessions" TO "service_role";



GRANT ALL ON TABLE "public"."telemetry_points" TO "anon";
GRANT ALL ON TABLE "public"."telemetry_points" TO "authenticated";
GRANT ALL ON TABLE "public"."telemetry_points" TO "service_role";



GRANT ALL ON TABLE "public"."tracks" TO "anon";
GRANT ALL ON TABLE "public"."tracks" TO "authenticated";
GRANT ALL ON TABLE "public"."tracks" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
































--
-- Dumped schema changes for auth and storage
--

CREATE OR REPLACE TRIGGER "on_auth_user_created" AFTER INSERT ON "auth"."users" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_user"();



CREATE POLICY "Anyone can upload an avatar." ON "storage"."objects" FOR INSERT WITH CHECK (("bucket_id" = 'avatars'::"text"));



CREATE POLICY "Avatar images are publicly accessible." ON "storage"."objects" FOR SELECT USING (("bucket_id" = 'avatars'::"text"));



CREATE POLICY "Give users access to own folder 1oj01fe_0" ON "storage"."objects" FOR DELETE USING ((("bucket_id" = 'avatars'::"text") AND (( SELECT ("auth"."uid"())::"text" AS "uid") = ("storage"."foldername"("name"))[1])));



CREATE POLICY "Give users access to own folder 1oj01fe_1" ON "storage"."objects" FOR SELECT USING ((("bucket_id" = 'avatars'::"text") AND (( SELECT ("auth"."uid"())::"text" AS "uid") = ("storage"."foldername"("name"))[1])));



